/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTransfersRouteImport } from './routes/app.transfers'
import { Route as AppSavingsRouteImport } from './routes/app.savings'
import { Route as AppMoreRouteImport } from './routes/app.more'
import { Route as AppLextxRouteImport } from './routes/app.lextx'
import { Route as AppInsuranceRouteImport } from './routes/app.insurance'
import { Route as AppHomeRouteImport } from './routes/app.home'
import { Route as AppCardsRouteImport } from './routes/app.cards'
import { Route as AppAiRouteImport } from './routes/app.ai'
import { Route as AppWalletCurrencyRouteImport } from './routes/app.wallet.$currency'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTransfersRoute = AppTransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => AppRoute,
} as any)
const AppSavingsRoute = AppSavingsRouteImport.update({
  id: '/savings',
  path: '/savings',
  getParentRoute: () => AppRoute,
} as any)
const AppMoreRoute = AppMoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => AppRoute,
} as any)
const AppLextxRoute = AppLextxRouteImport.update({
  id: '/lextx',
  path: '/lextx',
  getParentRoute: () => AppRoute,
} as any)
const AppInsuranceRoute = AppInsuranceRouteImport.update({
  id: '/insurance',
  path: '/insurance',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppCardsRoute = AppCardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => AppRoute,
} as any)
const AppAiRoute = AppAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppRoute,
} as any)
const AppWalletCurrencyRoute = AppWalletCurrencyRouteImport.update({
  id: '/wallet/$currency',
  path: '/wallet/$currency',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/ai': typeof AppAiRoute
  '/app/cards': typeof AppCardsRoute
  '/app/home': typeof AppHomeRoute
  '/app/insurance': typeof AppInsuranceRoute
  '/app/lextx': typeof AppLextxRoute
  '/app/more': typeof AppMoreRoute
  '/app/savings': typeof AppSavingsRoute
  '/app/transfers': typeof AppTransfersRoute
  '/app/wallet/$currency': typeof AppWalletCurrencyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/ai': typeof AppAiRoute
  '/app/cards': typeof AppCardsRoute
  '/app/home': typeof AppHomeRoute
  '/app/insurance': typeof AppInsuranceRoute
  '/app/lextx': typeof AppLextxRoute
  '/app/more': typeof AppMoreRoute
  '/app/savings': typeof AppSavingsRoute
  '/app/transfers': typeof AppTransfersRoute
  '/app/wallet/$currency': typeof AppWalletCurrencyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/ai': typeof AppAiRoute
  '/app/cards': typeof AppCardsRoute
  '/app/home': typeof AppHomeRoute
  '/app/insurance': typeof AppInsuranceRoute
  '/app/lextx': typeof AppLextxRoute
  '/app/more': typeof AppMoreRoute
  '/app/savings': typeof AppSavingsRoute
  '/app/transfers': typeof AppTransfersRoute
  '/app/wallet/$currency': typeof AppWalletCurrencyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/ai'
    | '/app/cards'
    | '/app/home'
    | '/app/insurance'
    | '/app/lextx'
    | '/app/more'
    | '/app/savings'
    | '/app/transfers'
    | '/app/wallet/$currency'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/login'
    | '/app/ai'
    | '/app/cards'
    | '/app/home'
    | '/app/insurance'
    | '/app/lextx'
    | '/app/more'
    | '/app/savings'
    | '/app/transfers'
    | '/app/wallet/$currency'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/ai'
    | '/app/cards'
    | '/app/home'
    | '/app/insurance'
    | '/app/lextx'
    | '/app/more'
    | '/app/savings'
    | '/app/transfers'
    | '/app/wallet/$currency'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/transfers': {
      id: '/app/transfers'
      path: '/transfers'
      fullPath: '/app/transfers'
      preLoaderRoute: typeof AppTransfersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/savings': {
      id: '/app/savings'
      path: '/savings'
      fullPath: '/app/savings'
      preLoaderRoute: typeof AppSavingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/more': {
      id: '/app/more'
      path: '/more'
      fullPath: '/app/more'
      preLoaderRoute: typeof AppMoreRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/lextx': {
      id: '/app/lextx'
      path: '/lextx'
      fullPath: '/app/lextx'
      preLoaderRoute: typeof AppLextxRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/insurance': {
      id: '/app/insurance'
      path: '/insurance'
      fullPath: '/app/insurance'
      preLoaderRoute: typeof AppInsuranceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/home': {
      id: '/app/home'
      path: '/home'
      fullPath: '/app/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cards': {
      id: '/app/cards'
      path: '/cards'
      fullPath: '/app/cards'
      preLoaderRoute: typeof AppCardsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ai': {
      id: '/app/ai'
      path: '/ai'
      fullPath: '/app/ai'
      preLoaderRoute: typeof AppAiRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/wallet/$currency': {
      id: '/app/wallet/$currency'
      path: '/wallet/$currency'
      fullPath: '/app/wallet/$currency'
      preLoaderRoute: typeof AppWalletCurrencyRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAiRoute: typeof AppAiRoute
  AppCardsRoute: typeof AppCardsRoute
  AppHomeRoute: typeof AppHomeRoute
  AppInsuranceRoute: typeof AppInsuranceRoute
  AppLextxRoute: typeof AppLextxRoute
  AppMoreRoute: typeof AppMoreRoute
  AppSavingsRoute: typeof AppSavingsRoute
  AppTransfersRoute: typeof AppTransfersRoute
  AppWalletCurrencyRoute: typeof AppWalletCurrencyRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiRoute: AppAiRoute,
  AppCardsRoute: AppCardsRoute,
  AppHomeRoute: AppHomeRoute,
  AppInsuranceRoute: AppInsuranceRoute,
  AppLextxRoute: AppLextxRoute,
  AppMoreRoute: AppMoreRoute,
  AppSavingsRoute: AppSavingsRoute,
  AppTransfersRoute: AppTransfersRoute,
  AppWalletCurrencyRoute: AppWalletCurrencyRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
